name: CI to Docker hub 

on:

  push:

    branches: [ master ]

  steps:

      -

        name: Login to DockerHub

        uses: docker/login-action@v1 

        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}

          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # -
      #   name: Build
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: false
      #     tags: kasiatemp/ng-update:latest
      #   env:
      #     NATIONAL_GRID_DB_JOB: ${{ secrets.NATIONAL_GRID_DB_JOB}}
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
