name: update carbon intensity data

on:
  push:
  #schedule:  
    #- cron:  '0 */1 * * *'
    branches: master
jobs:
  run_container:
    runs-on: ubuntu-latest
    container:
      image: kasiatemp/ng-update:mini
      env:
          MYPASS: ${{ secrets.PWD}}
    steps:
         - name: Run schedule
           run: |
             Rscript /home/schedule/daily-update-db.R
