name: CI to Docker hub 
on:
  push:
    branches: [ master ]
steps:
  name: Login to DockerHub
  uses: docker/login-action@v1 
  with:
    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
