name: refresh data 
on: push
jobs:
  build:
    name: refresh the data
    runs-on: ubuntu-18.04
    container:
     image: kasiatemp/update-ng:latest
    env:
        NATIONAL_GRID_DB_JOB: ${{ secrets.NATIONAL_GRID_DB_JOB}}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
      
